### ISSUE TITLE
int8_hnsw fails to merge documents

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#104617]
### Elasticsearch Version

8.12

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

Indexing `int8_hnsw` vectors may fail due to merging failures.

### Steps to Reproduce

 - Use `int8_hnsw` vectors
 - Continually index and merge vectors
 - May hit this particular bug

It is difficult to reproduce reliably via an API.

### Logs (if relevant)

```
Caused by: java.lang.NullPointerException: Cannot read field "values" because "this.current" is null at org.apache.lucene.codecs.KnnVectorsWriter$MergedVectorValues$MergedFloat32VectorValues.vectorValue(KnnVectorsWriter.java:225) ~[lucene-core-9.9.1.jar:?] at org.apache.lucene.util.ScalarQuantizer.fromVectors(ScalarQuantizer.java:256) ~[lucene-core-9.9.1.jar:?] at org.apache.lucene.codecs.lucene99.Lucene99ScalarQuantizedVectorsWriter.mergeAndRecalculateQuantiles(Lucene99ScalarQuantizedVectorsWriter.java:552)
```

Another example:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.DocIDMerger$Sub.nextMappedDoc()" because "this.current" is null
    at org.apache.lucene.index.DocIDMerger$SortedDocIDMerger.next(DocIDMerger.java:188) ~[lucene-core-9.9.1.jar:?]
    at org.apache.lucene.codecs.KnnVectorsWriter$MergedVectorValues$MergedFloat32VectorValues.nextDoc(KnnVectorsWriter.java:214) ~[lucene-core-9.9.1.jar:?]
    at org.apache.lucene.util.ScalarQuantizer.fromVectors(ScalarQuantizer.java:252) ~[lucene-core-9.9.1.jar:?]
    at org.apache.lucene.codecs.lucene99.Lucene99ScalarQuantizedVectorsWriter.mergeAndRecalculateQuantiles(Lucene99ScalarQuantizedVectorsWriter.java:552) ~[lucene-core-9.9.1.jar:?]
```

**Comment by benwtrent** [comment]
This bug exists in Lucene. The key part is where we sample the vectors. If there are deleted documents, we may attempt to sample a deleted document when sampling to create the quantiles. 

This may cause the vector iterator to go past where it should and thus hit an NPE.

This does not occur if `confidence_interval == 1` as we do not do any sampling in that scenario (simple min/max).

**Comment by benwtrent** [comment]
Related Lucene PR: https://github.com/apache/lucene/pull/13027

**Comment by benwtrent** [comment]
This has been fixed by: https://github.com/elastic/elasticsearch/pull/104753

**Comment by brianseeders** [comment]
This issue is still marked as a blocker for release v8.12.1 and the release process has started. Please review and determine whether the issue should block the release or if it is no longer considered a blocker.

**Comment by benwtrent** [comment]
@brianseeders we need to ensure the following commit is part of our release: https://github.com/elastic/elasticsearch/commit/4dc7d46c53486e4da4b30de1db7c7d3bb868a7fa

Otherwise this issue is still a blocker.

**Comment by benwtrent** [comment]
Confirmed the bug is fixed in 8.12 with commit: https://github.com/elastic/elasticsearch/commit/4dc7d46c53486e4da4b30de1db7c7d3bb868a7fa
