### ISSUE TITLE
[CI] ClientYamlTestSuiteIT classMethod failing

### ISSUE THREAD

**Issue by mosche** [elastic/elasticsearch#108730]
```
error:	
Unrecognized VM option 'UnlockDiagnosticVMOptions -XX:G1NumCollectionsKeepPinned=10000000'	
Error: Could not create the Java Virtual Machine.	
Error: A fatal exception has occurred. Program will exit.	
	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)	
	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)	
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)	
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)	
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/ucskslkbqyqvy/tests/:rest-api-spec:yamlRestTest/org.elasticsearch.test.rest.ClientYamlTestSuiteIT

**Reproduction line:**
```
null
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.test.rest.ClientYamlTestSuiteIT#classMethod`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('classMethod'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.test.rest.ClientYamlTestSuiteIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: An error occurred orchestrating test cluster.

  at __randomizedtesting.SeedInfo.seed([C935A8A6D5BD5198]:0)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.execute(LocalClusterHandle.java:233)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.writeUnicastHostsFile(LocalClusterHandle.java:214)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.waitUntilReady(LocalClusterHandle.java:155)
  at org.elasticsearch.test.cluster.local.LocalClusterHandle.start(LocalClusterHandle.java:76)
  at org.elasticsearch.test.cluster.local.LocalElasticsearchCluster$1.evaluate(LocalElasticsearchCluster.java:38)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.lang.RuntimeException: Elasticsearch process died while waiting for ports file. See console output for details.

    at org.elasticsearch.test.cluster.local.LocalClusterFactory$Node.lambda$waitUntilReady$0(LocalClusterFactory.java:201)
    at org.elasticsearch.test.cluster.util.Retry.lambda$retryUntilTrue$0(Retry.java:33)
    at org.elasticsearch.test.cluster.util.Retry.lambda$getValueWithTimeout$1(Retry.java:47)
    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    at java.lang.Thread.run(Thread.java:1583)

```

**Comment by mosche** [comment]
cc @rjernst

**Comment by rjernst** [comment]
Addressed by https://github.com/elastic/elasticsearch/pull/108689

**Comment by brianseeders** [comment]
@rjernst this is still happening

https://gradle-enterprise.elastic.co/s/mqoqtbj2kiixs/tests/task/:rest-api-spec:yamlRestTest/details/org.elasticsearch.test.rest.ClientYamlTestSuiteIT?top-execution=1

**Comment by mosche** [comment]
The fix in #108641 wasn't backported to 7.17

Also interesting, looks like these tests use a distrib without a bundled JDK.

```
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release	

Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]	
output:	
error:	
Unrecognized VM option 'UnlockDiagnosticVMOptions -XX:G1NumCollectionsKeepPinned=10000000'	
Error: Could not create the Java Virtual Machine.	
Error: A fatal exception has occurred. Program will exit.	
	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)	
	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)	
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)	
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)	
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
```

**Comment by rjernst** [comment]
The fix was backported, it was just done (unintentionally) as part of another change...
https://github.com/elastic/elasticsearch/commit/6f20cba5a1c94440fbe0e42380bd495667dd5ecf#diff-63b83abc508a8f7b1491b41c0823f2969851e438226301a2accd1efe7a39dcef

Note that SystemJvmOptions doesn't exist in 7.17, so the change was made directly in jvm.options there.

Are we sure this is still failing?

**Comment by rjernst** [comment]
I don't see this in recent failure history, so closing again.
