### ISSUE TITLE
`date` field types fail to index specific malformed data even with `ignore_malformed` enabled

### ISSUE THREAD

**Issue by lkts** [elastic/elasticsearch#109539]
### Elasticsearch Version

8.14

### Java Version

_bundled_

### OS Version

-

### Problem Description

As noticed in #109410 if a value of `date` or `date_nanos` field is an object, indexing such field will fail even with `ignore_malformed` enabled. This behavior differs from other field types like numbers.

### Steps to Reproduce

```
PUT /my_index
{
  "mappings": {
      "properties": {
          "date": {
              "type": "date",
              "ignore_malformed": true
          }
        }
    }
  }
}

// OK
PUT my_index/_doc/1
{
  "date": "hello"
}

// Fails
PUT my_index/_doc/2
{
  "date": {"string": "hello"}
}
```

**Comment by martijnvg** [comment]
@lkts This is fixed for that #109410 is merged, right?

**Comment by lkts** [comment]
No, that PR does not fix it. The actual logic of ignore_malformed is not changed.
