### ISSUE TITLE
ESQL lookup join with lookup index results in duplicate set of rows.

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#118852]
Performing a lookup join between 2 distinct lookup indices results in duplicated set of rows in result set:
```
~ ᐅ curl -XPOST "${ES_URL}/_query?format=txt" -H 'Content-Type: application/json' -d'{"query": "FROM languages"}'
     code      | code.keyword  |   language    |language.keyword
---------------+---------------+---------------+----------------
en             |en             |English        |English         
es             |es             |Spanish        |Spanish         
fr             |fr             |French         |French          
~ ᐅ curl -XPOST "${ES_URL}/_query?format=txt" -H 'Content-Type: application/json' -d'{"query": "FROM countries"}'
     code      | code.keyword  |   countries   |countries.keyword
---------------+---------------+---------------+-----------------
en             |en             |England        |England          
es             |es             |Spain          |Spain            
fr             |fr             |France         |France           
~ ᐅ curl -XPOST "${ES_URL}/_query?format=txt" -H 'Content-Type: application/json' -d'{"query": "FROM countries | LOOKUP JOIN languages ON code"}'
     code      |   countries   |countries.keyword| code.keyword  |   language    |language.keyword
---------------+---------------+-----------------+---------------+---------------+----------------
en             |null           |null             |en             |English        |English         
es             |null           |null             |es             |Spanish        |Spanish         
fr             |null           |null             |fr             |French         |French          
en             |England        |England          |en             |English        |English         
es             |Spain          |Spain            |es             |Spanish        |Spanish         
fr             |France         |France           |fr             |French         |French    
```

**Comment by alex-spies** [comment]
I can reproduce this on main. Here's a complete reproducer:

```
$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/languages_lookup" -XPUT -d '{
  "mappings": {
        "properties": {"language_code": {"type": "keyword"}, "language_name":{"type": "keyword"}}}, "settings": {"index": {"mode": "lookup"}}}'

$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/languages_lookup2" -XPUT -d '{
  "mappings": {
        "properties": {"language_code": {"type": "keyword"}, "language_name":{"type": "keyword"}}}, "settings": {"index": {"mode": "lookup"}}}'

$ curl -u elastic:password -HContent-Type:application/json 'localhost:9200/languages_lookup/_doc?refresh' -d'{"language_code": "1", "language_name": "English"}'

$ curl -u elastic:password -HContent-Type:application/json 'localhost:9200/languages_lookup2/_doc?refresh' -d'{"language_code": "2", "language_name": "English2"}'

$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '
{
  "query": "from languages_lookup2 | rename language_name as ln | lookup join languages_lookup on language_code"
}
'

 language_code |      ln       | language_name 
---------------+---------------+---------------
1              |English        |English        
2              |English2       |null
```

**Comment by alex-spies** [comment]
I think when a lookup index is used in the FROM, we do not construct the data node requests correctly. It nearly looks like we dump all the lookup index nodes into the `FROM` side in the ComputeService:
![Image](https://github.com/user-attachments/assets/17a6134e-8054-4e96-8569-96d78d058b0c)

When I generalize the example above and perform 2 lookups on distinct lookup indices when yet another lookup index is in the `FROM`, I get the rows from all those indices mashed together.

**Comment by alex-spies** [comment]
That may already be solved by https://github.com/elastic/elasticsearch/pull/118768, but we need to add tests to confirm. I.e. a test case that uses multiple distinct lookup indices in the same query, both in the FROM and in the LOOKUP JOINs.

**Comment by ivancea** [comment]
Looks like this is still happening in the current main.

A test like:
```
FROM languages_lookup_non_unique_key
| WHERE language_code == 1
| LOOKUP JOIN languages_lookup ON language_code
| KEEP language_code, language_name, country
| SORT language_code, language_name, country
;

language_code:integer | language_name:keyword       | country:text
1                     | English                     | Canada
1                     | English                     | United Kingdom
1                     | English                     | United States of America
1                     | English                     | null
;
```

Results in a duplicated last row
