### ISSUE TITLE
Use of pre and post filters throws "TokenStream contract violation: close() call missing"

### ISSUE THREAD

**Issue by jhariani** [elastic/elasticsearch#11947]
This happens when using the standard analyzer as a pre and post filter after a direct candidate generator (ES 1.6). When this query was run in a multi-node environment, the error seemed to persist and required a rolling restart.  For example: 

```json
{ "suggest" : {
    "text" : "pizeo",
    "simple_phrase" : {
      "phrase" : {
        "analyzer" : "english",
        "field" : "synopses",
        "direct_generator" : [ {
          "field" : "synopses",
          "suggest_mode" : "always",
          "min_word_length" : 1
        }, {
          "field" : "synopses",
          "suggest_mode" : "always",
          "min_word_length" : 1,
          "pre_filter" : "standard",
          "post_filter" : "standard"
        } ]
      }
    }
  }
}
```
Will throw this error:
```json
{
   "took": 21,
   "timed_out": false,
   "_shards": {
      "total": 4,
      "successful": 1,
      "failed": 3,
      "failures": [
         {
            "index": "project",
            "shard": 0,
            "status": 500,
            "reason": "IllegalStateException[TokenStream contract violation: close() call missing]"
         },
         {
            "index": "project",
            "shard": 2,
            "status": 500,
            "reason": "IllegalStateException[TokenStream contract violation: close() call missing]"
         },
         {
            "index": "project",
            "shard": 3,
            "status": 500,
            "reason": "IllegalStateException[TokenStream contract violation: close() call missing]"
         }
      ]
   },
   "suggest": {
      "simple_phrase": [
         {
            "text": "pizo",
            "offset": 0,
            "length": 4,
            "options": []
         }
      ]
   }
}
```

[2015-06-30 10:16:05,888][DEBUG][action.search.type       ] [Wiz Kid] [project][0], node[OhG1Vc65RPyjCcSlXDbCJQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@7bd06ad7] lastShard [true]
java.lang.IllegalStateException: TokenStream contract violation: close() call missing
	at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)
	at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:323)
	at org.apache.lucene.analysis.standard.StandardAnalyzer$1.setReader(StandardAnalyzer.java:133)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:147)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:119)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:115)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.preFilter(DirectCandidateGenerator.java:133)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.frequency(DirectCandidateGenerator.java:92)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator$2.nextToken(DirectCandidateGenerator.java:155)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:130)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:122)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:115)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.postFilter(DirectCandidateGenerator.java:148)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.drawCandidates(DirectCandidateGenerator.java:122)
	at org.elasticsearch.search.suggest.phrase.MultiCandidateGeneratorWrapper.drawCandidates(MultiCandidateGeneratorWrapper.java:52)
	at org.elasticsearch.search.suggest.phrase.NoisyChannelSpellChecker.getCorrections(NoisyChannelSpellChecker.java:116)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:98)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:54)
	at org.elasticsearch.search.suggest.Suggester.execute(Suggester.java:43)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:85)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:74)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:170)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:289)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:300)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by clintongormley** [comment]
@areek please could you investigate

**Comment by vreon** [comment]
We ran into this issue as well (also 1.6).

**Comment by aparo** [comment]
I ran in this issue with 2.0-beta2. With a similar configuration of @jhariani.
The shards are random failing executing many times the same call.
The fails are related to preFilter call in o.e.search.suggest.phrase.DirectCandidateGenerator.preFilter(DirectCandidateGenerator.java:115)

**Comment by mikemccand** [comment]
This was supposed to have been fixed in d97afd52f3e743547277c8fea6fb02fbe2bdc1ff ... and that fix is in 2.0-beta2 ... @aparo can you post more details about the exception?  Was there an initial exception before you hit the `close() call missing`?

**Comment by jelmerk** [comment]
We are still seeing this issue on elastic 1.7.1 when using the following generator in a phrase suggester

       {
          "field" : "title.reversed",
          "prefix_length" : 2,
          "pre_filter" : "reverser",
          "post_filter" : "reverser"
        }

Where reverser looks like this :

        "reverser": {
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "dutch_stopwords",
            "asciifolding",
            "reverse"
          ]
        }

**Comment by clintongormley** [comment]
@jelmerk the fix is in 2.0

**Comment by genafox** [comment]
Hi,
I`ve got the same error on elasticsearch 6.2.4:

Index:
`PUT phrase-suggester-test-index
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "analysis": {
        "analyzer": {
          "trigram": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "standard",
              "shingle"
            ]
          },
          "reverse": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "standard",
              "reverse"
            ]
          },
          "wordnet-synonym-analyzer": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "lowercase",
              "synonym"
            ]
          }
        },
        "filter": {
          "shingle": {
            "type": "shingle",
            "min_shingle_size": 2,
            "max_shingle_size": 3
          },
          "synonym": {
            "type": "synonym",
            "format": "wordnet",
            "synonyms_path": "analysis/wn_s.pl"
          }
        }
      }
    }
  },
  "mappings": {
    "test": {
      "properties": {
        "title": {
          "type": "text",
          "fields": {
            "trigram": {
              "type": "text",
              "analyzer": "trigram"
            },
            "reverse": {
              "type": "text",
              "analyzer": "reverse"
            },
            "synonym": {
              "type": "text",
              "analyzer": "wordnet-synonym-analyzer"
            }
          }
        }
      }
    }
  }
}`

Data:
`POST phrase-suggester-test-index/test?refresh=true
{"title": "Captain America"}
`

Request:
`POST phrase-suggester-test-index/_search
{
  "suggest": {
    "text" : "captain usa",
    "simple_phrase" : {
      "phrase" : {
        "field" :  "title.synonym",
        "size" :   1,
        "direct_generator" : [{
          "field" : "title.synonym",
          "suggest_mode" : "always",
          "pre_filter" : "wordnet-synonym-analyzer",
          "post_filter" : "wordnet-synonym-analyzer"
        }],
        "collate": {
          "query": { 
            "source" : {
              "match": {
                "{{field_name}}" : "{{suggestion}}" 
              }
            }
          },
          "params": {"field_name" : "title"}, 
          "prune": true 
        }
      }
    }
  }
}`

Response:
`{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "TokenStream contract violation: close() call missing"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "phrase-suggester-test-index",
        "node": "SKe2nqf-QSuSialfTHt2jA",
        "reason": {
          "type": "illegal_state_exception",
          "reason": "TokenStream contract violation: close() call missing"
        }
      }
    ]
  },
  "status": 500
}`

Logs:
`[2018-05-10T12:45:11,479][WARN ][r.suppressed             ] path: /phrase-suggester-test-index/_search, params: {index=phrase-suggester-test-index}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:274) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:132) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:243) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:107) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:49) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:217) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:171) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:49) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:217) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:527) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1098) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1191) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1175) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.SearchTransportService$6$1.onFailure(SearchTransportService.java:385) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:324) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:318) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:312) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1002) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:672) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.2.4.jar:6.2.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.elasticsearch.ElasticsearchException$1: TokenStream contract violation: close() call missing
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:619) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.SearchPhaseExecutionException.guessRootCauses(SearchPhaseExecutionException.java:170) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.SearchPhaseExecutionException.getCause(SearchPhaseExecutionException.java:111) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:139) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:326) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:64) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:333) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:232) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:217) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) ~[log4j-core-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:217) ~[log4j-api-2.9.1.jar:2.9.1]
	at org.elasticsearch.common.logging.PrefixLogger.logMessage(PrefixLogger.java:102) ~[elasticsearch-core-6.2.4.jar:6.2.4]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116) ~[log4j-api-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100) ~[log4j-api-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1989) ~[log4j-api-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1851) ~[log4j-api-2.9.1.jar:2.9.1]
	at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2589) ~[log4j-api-2.9.1.jar:2.9.1]
	at org.elasticsearch.rest.BytesRestResponse.build(BytesRestResponse.java:133) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:96) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.rest.BytesRestResponse.<init>(BytesRestResponse.java:91) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:58) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:91) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:222) ~[elasticsearch-6.2.4.jar:6.2.4]
	... 28 more
Caused by: java.lang.IllegalStateException: TokenStream contract violation: close() call missing
	at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:412) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:165) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.analyze(DirectCandidateGenerator.java:316) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.preFilter(DirectCandidateGenerator.java:149) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.frequency(DirectCandidateGenerator.java:110) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.MultiCandidateGeneratorWrapper.frequency(MultiCandidateGeneratorWrapper.java:46) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.CandidateGenerator.createCandidate(CandidateGenerator.java:40) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.NoisyChannelSpellChecker$1.nextToken(NoisyChannelSpellChecker.java:95) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.analyze(DirectCandidateGenerator.java:333) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.NoisyChannelSpellChecker.getCorrections(NoisyChannelSpellChecker.java:65) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:96) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:52) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.Suggester.execute(Suggester.java:39) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:64) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:95) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:307) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:340) ~[elasticsearch-6.2.4.jar:6.2.4]
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:316) ~[elasticsearch-6.2.4.jar:6.2.4]
	... 9 more`
