### ISSUE TITLE
 elasticsearch/distribution/src/main/packaging/scripts/preinst is plain wrong

### ISSUE THREAD

**Issue by jelmd** [elastic/elasticsearch#14630]
elasticsearch-2.0.0.deb

elasticsearch/distribution/src/main/packaging/scripts/preinst is plain wrong, because (at least on debian/ubuntu systems) the ES_ENV_FILE (/etc/default/elasticsearch) is not yet in place/configured and therefore this script now modifies the system in a manner, which might not be allowed per system/org policy!!!

If you wanna try, e.g. on ubuntu:

```
apt-get purge elasticsearch
dpkg --unpack elasticsearch-2.0.0.deb
sed -r -e '/^#?ES_(USER|GROUP)=/ { s,^#,, ; s,=.*,=esearch, }' -i /etc/default/elasticsearch.dpkg-new
sed -e '/rmdir/ s,$, || true,' -i /var/lib/dpkg/info/elasticsearch.postrm       # yepp, buggy
dpkg --configure elasticsearch
```

**Comment by clintongormley** [comment]
Hi @jelmd 

Sorry to be obtuse, but could you talk me through the problem here? I'm not following.

**Comment by jelmd** [comment]
Hi,

Have a look at http://man7.org/linux/man-pages/man1/dpkg.1.html#ACTIONS , option -i : here you can see the single steps executed, when a package gets installed. Obviously the package's preinst script gets executed BEFORE the package puts /etc/default/elasticsearch into place (this happens in step 6) aka configuration). However, in line 19 of the preinst script you are trying to source in this file and thus you created a chicken and egg problem. 

Last but not least now it is not possible anymore, to do a `dpkg --unpack e*.deb`, fix the script//etc/default/elasticsearch before it gets installed, i.e. when one runs finally the `dpkg --configure e*` ...

The 1.x packages did it right, 2.0.0 packages are plain wrong.

**Comment by jordansissel** [comment]
@jelmd I took a glance at the file you mentioned, and it seems ok to me.

The way I read it, the env file is only loaded if it exists. 

Is the problem that the package would create a user 'elasticsearch' because the value ES_USER is unlikely to be modified by the operator at the time of `preinst` ?

**Comment by rjernst** [comment]
I think this was fixed by #28918 (@jasontedor please correct me if I'm wrong). `preinst` no longer sources any files.

**Comment by jelmd** [comment]
The problem was not fixed. Now it is even worse, because it uses hard coded values instead for no reason.

**Comment by jasontedor** [comment]
@jelmd We want to listen to you and we are open to feedback, but I encourage you to understand that we do not make any changes for "no reason" and that you state reasoned objections to those changes (namely, a concrete problem that you're trying to solve that can not be solved because of those changes).

**Comment by jelmd** [comment]
Hmmm, thought the issue was explained well - please scroll to the top of the page. Please tell me, what is missing/not understood.
BTW: "no reason" refers to: if the SW would be properly assembled and related scripts properly written, there would be no reason to throw away required customizations like this in a BFH manner.

**Comment by jasontedor** [comment]
@jelmd Yes, it's unclear. The initial problem statement is:

> elasticsearch/distribution/src/main/packaging/scripts/preinst is plain wrong, because (at least on debian/ubuntu systems) the ES_ENV_FILE (/etc/default/elasticsearch) is not yet in place/configured and therefore this script now modifies the system in a manner, which might not be allowed per system/org policy!!!

We no longer source the environment file, therefore it does not matter whether or not it is in place. You say something about violating system policy, but it is not clear what is being violated, and how sourcing the environment file relates to that. Your next [comment](https://github.com/elastic/elasticsearch/issues/14630#issuecomment-158853711) elaborates only about the problems that arise from sourcing the environment file before it exists, which again does not matter if we no longer source the environment file. Then you [say](https://github.com/elastic/elasticsearch/issues/14630#issuecomment-372596456):

> The problem was not fixed.

which again, as far as I can discern from your problem statement is that we source the environment file before it exists. Except, no more with the change that was referenced.

Which brings me to: if this change did not solve the problem, I don't understand the problem which is why I ask you for a concrete problem statement that is not solved by these changes.
