### ISSUE TITLE
Add a note about the different deb repo source for installing pre-releases  

### ISSUE THREAD

**Issue by suyograo** [elastic/elasticsearch#20593]
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html doc page specifies how to install an ES deb by adding the repo to source list.

`echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list`

This will not work for pre-releases as we use a different repo: `https://artifacts.elastic.co/packages/5.x-prerelease/apt`

The docs need to be updated to add a note about installing the pre-releases.

**Comment by rjernst** [comment]
I don't really know the best way to convey that prereleases have a different repo in the docs. Maybe @clintongormley has ideas.

**Comment by clintongormley** [comment]
I've changed the URLs in the 5.0 and master branches to use -prerelease, and opened blocker PRs to change them back before GA #20604 and #20605

**Comment by tomas-mazak** [comment]
On the docs page for 5.x and 5.0 there's still a non-working version "deb https://artifacts.elastic.co/packages/5.x/apt stable main"

**Comment by clintongormley** [comment]
@tomas-mazak this is fixed by https://github.com/elastic/elasticsearch/pull/20644

**Comment by tomas-mazak** [comment]
@clintongormley I still see the confusion here: https://www.elastic.co/guide/en/elasticsearch/reference/5.x/deb.html

**Comment by clintongormley** [comment]
@tomas-mazak the docs had not yet been rebuilt.  Look now: https://www.elastic.co/guide/en/elasticsearch/reference/5.x/deb.html
