### ISSUE TITLE
High shard count in an index prevents upgrading to 5.0.0

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#21114]
**Elasticsearch version**: 5.0.0

**OS version**: OSX

**Description of the problem including expected versus actual behavior**:
A poorly configured high-shard-count 2.4 index can prevent 5.0 from starting with little method for recovery

**Steps to reproduce**:
1. Start 2.4 node
2. `PUT /foo -d '{ "settings" : { "number_of_shards" : 2000 } }'`
3. Migrate 2.4 data path to 5.0
4. Attempt to start Elasticsearch

**Provide logs (if relevant)**:
https://gist.github.com/eskibars/78ef933939e0052db3730bd6a22f3eb9

Attempting to bypass via `/bin/elasticsearch -Eindex.max_number_of_shards=5000` doesn't allow elasticsearch to set up, since this is an index setting that can't be set at the node level.

Unfortunately, the result of this can leave your cluster in an unrecoverable state.  Consider the following scenario:
1. Start 2.4 node
2. `PUT /abc`
3. `PUT /abc/t/1 -d '{ "foo": "bar" }'`
4. `PUT /foo -d '{ "settings" : { "number_of_shards" : 2000 } }'`
5. Stop 2.4 node
6. Migrate 2.4 data path to 5.0
7. Attempt to start Elasticsearch.  Failure comes as described above

Now you're in trouble unless you took snapshots.  The shard check/exit that Elasticsearch does in (7) came _after_ Elasticsearch 5.0 renamed your `abc` index/directory, so if you try to revert back to 2.4 at this point, it's treated as a dangling index and `/abc/_search` produces 0 results

**Comment by s1monw** [comment]
first, I am not sure this is a bug, if you wanna run an index with that many shards you gotta set it up accordingly. Yet, I think we need to throw  better exception.

> Now you're in trouble unless you took snapshots. The shard check/exit that Elasticsearch does in (7) came after Elasticsearch 5.0 renamed your abc index/directory, so if you try to revert back to 2.4 at this point, it's treated as a dangling index and /abc/_search produces 0 results

very misleading comment almost reckless? The node must be started with `export ES_JAVA_OPTS="-Des.index.max_number_of_shards=128”` as documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules.html)

that said I am not sure we should auto-upgrade old indices since it is just asking for trouble down the road unless the setting is set. I think we need to do this differently and provide a different error message if there is an index in the cluster that has `too many shards`

**Comment by nik9000** [comment]
If you can work around this by adding `-Des.index.max_number_of_shards= 2000` to ES_JAVA_OPTS I think we're good so long as we make sure to tell people that in the startup failure *and* we should tell them exactly why it is a bad idea. That way their upgrade will be exciting rather than a catastrophe.

**Comment by s1monw** [comment]
@nik9000 I don't think it's a showstopper, we can target this for 5.0.1

**Comment by nik9000** [comment]
++

**Comment by bleskes** [comment]
+1 for this not being a blocker. The impact in real life is likely minimal. I opened https://github.com/elastic/elasticsearch-migration/issues/83 so the migration plugin will tell you about this.

**Comment by bleskes** [comment]
https://github.com/elastic/elasticsearch-migration/issues/83 was fixed by @eskibars and we released a new version of the migration plugin with the fix

**Comment by rjernst** [comment]
I believe this is still an issue and the PR #21269 should be revived to fix it.

**Comment by gwbrown** [comment]
This issue describes a specific problem with 2.4->5.x upgrades, for which there is a warning in the 2.4 migration assistant. Both of the versions in question have long since passed their EOL date, and as such, we are not going to address this issue with any code changes. As such, I'm going to close this issue.

If we believe there are remaining issues with inappropriately archiving index settings, that should be raised as a new issue, with details as relate to a maintained version of Elasticsearch.
