### ISSUE TITLE
resource.reload.interval not configurable

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#22814]
**Elasticsearch version**:
5.1.1

In order to speed up the reloading of scripts, it seems that it's possible to do this:

```
resource.reload.interval.medium: "2s"
```

Which works great - but there are no clear docs on how to use these settings, in particular:
- How to change the default interval from medium
- What is the purpose of the `resource.reload.interval` setting.

Start ES with:

```
resource.reload.interval: "2s"
```

Results in:

```
Caused by: java.lang.IllegalArgumentException: unknown setting [resource.reload.interval] did you mean any of [resource.reload.interval.low, resource.reload.interval.high, resource.reload.interval.medium, resource.reload.enabled]?
```

**Comment by pickypg** [comment]
I believe this is because the `resource.reload.interval` is not given `NodeScope`, unlike the other settings.

**Comment by olalonde** [comment]
Does that mean that the documentation here is incorrect? https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#reload-scripts

It mentions setting `resource.reload.interval`.

**Comment by dakrone** [comment]
This is already fixed, see: https://github.com/elastic/elasticsearch/blob/07f67cd8b545a14867496800407644d849671b77/core/src/main/java/org/elasticsearch/watcher/ResourceWatcherService.java#L72-L73

**Comment by acarstoiu** [comment]
This is **not** solved. This exception
```
 java.lang.IllegalArgumentException: unknown setting [resource.reload.interval] did you mean any of [resource.reload.interval.low, resource.reload.interval.high, resource.reload.interval.medium, resource.reload.enabled]?
```
is still thrown. Please update the docs, at the very least.
