### ISSUE TITLE
Build is failing with Gradle 4.2

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#26840]
Not sure what causes it but when I run:

```sh
gradle :plugins:repository-azure:check
```

I'm getting (tested on 5.6, 6.0 and 6.x branches):

```
* What went wrong:
Execution failed for task ':plugins:repository-azure:integTestCluster#installRepositoryAzurePlugin'.
> A problem occurred starting process 'command '/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch/es-5.x/elasticsearch/plugins/repository-azure/build/cluster/integTestCluster node0/elasticsearch-5.6.3-SNAPSHOT/bin/elasticsearch-plugin''
```

Note that on 6.0 and 6.x the message is a bit different as it fails when running `bin/elasticsearch-keystore`. I checked manually the directory and I'm able to run `bin/elasticsearch-plugin` or `bin/elasticsearch-keystore` manually.

```sh
$ gradle -version

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64
```

Running with `gradlew` works:

```sh
./gradlew :plugins:repository-azure:check
```

gradlew reports a 3.3 version of Gradle.

**Comment by yeikel** [comment]
I can confirm this is happening. I was able to build in 4.1

Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9 (Oracle Corporation 9+181)
OS:           Windows 10 10.0 amd64
------------------------------------------------------------

**Comment by dnhatn** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/27087

**Comment by jasontedor** [comment]
This is not fixed, the build is still failing with Gradle 4.2. We have to figure out whether it's a problem on our end, or Gradle's end and address either way.

**Comment by AmishP** [comment]
I've just got this same error using Gradle Gradle 4.2.1 but works with Gradle 4.1.

**Comment by dadoonet** [comment]
I just tested it with:

```
$ gradle -version

------------------------------------------------------------
Gradle 4.3
------------------------------------------------------------

Build time:   2017-10-30 15:43:29 UTC
Revision:     c684c202534c4138b51033b52d871939b8d38d72

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.13 x86_64
```

And we still have the same problem.

**Comment by dadoonet** [comment]
Strange. I actually ran it again with:

```sh
gradle :plugins:ingest-attachment:clean
gradle :plugins:ingest-attachment:check
```

And it passed. Not sure what happen on my previous try.
I'm going to clean the whole build, restart again and update this issue. Stay tuned...

**Comment by dadoonet** [comment]
Here is what I just ran:

```sh
gradle clean
gradle :plugins:ingest-attachment:check
```

This is passing with Gradle 4.3 so I believe we can allow now builds with 4.3?

**Comment by fgil-receptiviti** [comment]
@dadoonet Thanks! It's working with gradle 4.3 for me.
