### ISSUE TITLE
no log4j2.properties found; tried [/usr/share/elasticsearch/config] and its subdirectories

### ISSUE THREAD

**Issue by bainim** [elastic/elasticsearch#27605]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
5.2.2
**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
ubuntu 14.04-server 
**Description of the problem including expected versus actual behavior**:
no log4j2.properties found; tried [/usr/share/elasticsearch/config] and its subdirectories
**Steps to reproduce**:

docker pull elasticsearch:5.2.2

docker run -d --name=ElasticSearch --restart=unless-stopped -v /myfolder/elasticsearch/config:/usr/share/elasticsearch/config -v /var/docker/containers/elasticsearch/data:/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 -e ES_JAVA_OPTS="-Xms8g -Xmx8g" elasticsearch

docker ps :
e1425864a03c elasticsearch "/docker-entrypoin..." 4 hours ago Up 3 hours 0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp ElasticSearch

after that i want to access , myadresse ip :9200 but i got no thing

docker logs e1425864a03c

**Provide logs (if relevant)**:

**Comment by markharwood** [comment]
Thanks for the report. We've already addressed this in https://github.com/elastic/elasticsearch-docker/issues/78 so closing this as a duplicate.

**Comment by bainim** [comment]
sorry but i can't understand the solution what i should do exactelly?

**Comment by markharwood** [comment]
>what i should do exactelly?

Upgrade - I'm told this was a bug, addressed in >=5.5.0

**Comment by bainim** [comment]
but now i remove  the container (volume) and i execute :
 docker pull elasticsearsh:latest 
and it's still the same error

**Comment by jasontedor** [comment]
You're not pulling the official image at all. If you need more help, please check the docs or ask for help on the [forum](https://discuss.elastic.co). We reserve GitHub for confirmed bugs and feature requests, not general help.

**Comment by bainim** [comment]
ok thank you
