### ISSUE TITLE
[BUG] Fuzziness to XContext not working with custom LOW HIGH param

### ISSUE THREAD

**Issue by MuffinUser** [elastic/elasticsearch#33454]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4 possibly before

**Plugins installed**: none

**JVM version** (`java -version`): Java 8

**OS version** (`uname -a` if on a Unix-like system): Windows

**Description of the problem including expected versus actual behavior**:
If a custom Low and Highlimit are set for a Fuzziness e.g "AUTO3:8" the correct Object is instantiated. But when this Object is read out for a Query, it just puts out "fuzziness:AUTO" instead of "fuzziness:AUTO3:8".

**Steps to reproduce**:

 1. create Object of Fuzziness with Custom LOW and HIGH (new Fuzziness("AUTO3:8")
 2. use in Query
 3.Inspect query

**Provide logs (if relevant)**:
![2018-09-06_09h13_58](https://user-images.githubusercontent.com/32880344/45141839-47691280-b1b7-11e8-9acf-7ad32e75d147.png)

**Comment by AFurtner** [comment]
I can confirm this Bug.
The 1st step to reproduce would be correct `Fuzziness.build("AUTO:3,8")`. Instantiating with new Funzziness("AUTO:3,8") will not work anyway. But the problem remains. It's not generating the correct JSON output for ES Rest API but ignoring the lowDistance and highDistance values.
Proposed patch could be: in method toXContent(XContentBuilder builder, Params params) replace
`        builder.field(X_FIELD_NAME, fuzziness);`
with
 `       builder.field(X_FIELD_NAME, asString());`
as asString() seems to respect low and high distance values. I don't know if this patch could have any unwanted side effects?

**Comment by MuffinUser** [comment]
https://github.com/MuffinUser/elasticsearch/commit/ce7d5e3c867277e7c5f9102d78acfb35ea27ec98
Here is a commit. But it was to painful to fill out all the agreements and stuff to create the PR.

**Comment by fadijabi** [comment]
Is this fixed yet? I am on 6.6.1

**Comment by andyb-elastic** [comment]
Yes, this is fixed in 6.0 and later - it was fixed by @cbuescher in https://github.com/elastic/elasticsearch/pull/35807

**Comment by fadijabi** [comment]
It is not fixed for me. I am using elasticsearch 6.6.1 and I still feel it is still defaulting to AUTO:3,6

I have a field named "featuretype" of type "keyword" and if I execute 

`GET kf-master/_search
{
  "query": {
    "match": {
      "featuretype": {
        "query": "Uniy",
        "operator": "AND",
        "fuzziness": "auto:5,8",
        "prefix_length": 1,
        "fuzzy_transpositions": false
      }
    }
  }
}`

I still get results where featuretype are "Unit". As per my understanding AUTO:5,8 will

0..4
Must match exactly
5..7
One edit allowed
>7
Two edits allowed

Any help is much appreciated.

**Comment by fadijabi** [comment]
Ping?

**Comment by cbuescher** [comment]
@fadijabi from a quick look, this might be a related issue that was so far masked by the parsing problem that was fixed in #35807.
Would you mind opening an issue for further investigation?
