### ISSUE TITLE
SQL: selecting a literal from grouped by query generates error

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#41413]
```
sql> select 1 from test_emp group by gender;
Bad request [Found 1 problem(s)
line 1:33: Unknown column [gender], did you mean [gender]?]
```

**Comment by codebird** [comment]
I was thinking of a solution like this:

https://github.com/elastic/elasticsearch/compare/master...codebird:issue%2341413?expand=1

Logic behind it, is that if all we're selecting are literals, then resolved should become all acceptable fields in our field list. Now for some reason, this is considering the group by field as a literal too. so this:

`select 1 from testing group by name`

is being considered like this:

`select 1 from testing group by 'name'`

So I wanted to get some input on my approach before going forward.

**Comment by matriv** [comment]
@astefan this is similar to #34583, Isn't it? Should we close the old one as a duplicate?

**Comment by astefan** [comment]
@codebird thank you for looking at this. We haven't yet started looking at the issue or the proposed PR.

Not sure @matriv, but I'd be cautious and keep both. There are other issues around literals in different scenarios, as well.

**Comment by matriv** [comment]
The status of such queries has been changed. No error is thrown but instead only one row is returned, independently of the buckets that the group by would return, since they are wrongly translated to `LocalExec` plans.

**Comment by codebird** [comment]
my pull request solves this issue, but for some reason it has been forgotten.

**Comment by matriv** [comment]
Hi @codebirg,

Apologies for the long delay, but we didn't forget your PR. We wanted to wait for the refactoring merged with: #49570 which simplifies the code in many aspects, so that we could address such issues in a less "hacky" way.

**Comment by codebird** [comment]
I'll merge into my branch and check it out @matriv will try to check it out this week

**Comment by matriv** [comment]
Thank you @codebird !

**Comment by codebird** [comment]
@matriv all things were already fixed, except #41951, and aliasing a literal

Ex:
`SELECT COUNT(*) as c FROM test WHERE ABS(int) > 0 GROUP BY int`
`SELECT 1 as t FROM test GROUP BY int`


 I updated my pull request accordingly...

**Comment by matriv** [comment]
@codebird 
```SELECT 1 as t FROM test GROUP BY int```
is not fixed. It doesn't throw an Exception but it returns only one row, where it should return one row per group (created by values of `int` in this case)

**Comment by codebird** [comment]
thank you for looking into it @matriv, this slipped through I had it fixed this time, seems I forgot to move some of the code. I'll fix it today and start working on tests.

**Comment by codebird** [comment]
@matriv this issue `SELECT 1 as t FROM test GROUP BY int` is also on this query `SELECT 1 FROM test GROUP BY int`, I am still trying to figure out, but notice that both queries return the same result. `SELECT 1 FROM test GROUP BY int` <- this is currently on master.

**Comment by codebird** [comment]
the issue with these 2 queries was fixed. If you can check out my solution. I'll go on with writing the tests.

**Comment by matriv** [comment]
`master` : 45b85809678b34a448639a420b97e25436ae851f
`7.x` : 5b32d112e178539a8ed98b7148a43241cea9a0da
`7.6` : 967f70284211d57f4488c7b15c1d33e3bbdc531a
