### ISSUE TITLE
Repository plugins thirdPartyAudit failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#44066]
```
11:17:38 Missing classes:
11:17:38   * com.amazonaws.services.kms.AWSKMS
11:17:38   * com.amazonaws.services.kms.AWSKMSClient
11:17:38   * com.amazonaws.services.kms.model.DecryptRequest
11:17:38   * com.amazonaws.services.kms.model.DecryptResult
11:17:38   * com.amazonaws.services.kms.model.EncryptRequest
11:17:38   * com.amazonaws.services.kms.model.EncryptResult
11:17:38   * com.amazonaws.services.kms.model.GenerateDataKeyRequest
11:17:38   * com.amazonaws.services.kms.model.GenerateDataKeyResult
11:17:38 
11:17:38 > Task :plugins:repository-s3:thirdPartyAudit FAILED
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob+third-party-tests-s3/7/console
https://scans.gradle.com/s/sgpbiupayjavq

Probably caused by #43671

**Comment by davidkyle** [comment]
More failures from a different project but looks related

```
07:24:40 > Task :plugins:discovery-ec2:thirdPartyAudit FAILED
07:24:40 Unnecessary exclusions, following classes are not missing:
07:24:40    * com.amazonaws.jmespath.JmesPathIdentity
07:24:40   * com.amazonaws.jmespath.JmesPathLengthFunction
07:24:40   * com.amazonaws.jmespath.JmesPathLiteral
07:24:40   * com.amazonaws.jmespath.OpGreaterThan
07:24:40   * javax.servlet.ServletContextEvent
07:24:40   * javax.servlet.ServletContextListener
07:24:40   * javax.xml.bind.DatatypeConverter
07:24:40   * javax.xml.bind.JAXBContext
07:24:40   * org.apache.avalon.framework.logger.Logger
07:24:40   * org.apache.log.Hierarchy
07:24:40   * org.apache.log.Logger
07:24:40   * software.amazon.ion.IonSystem
07:24:40   * software.amazon.ion.IonWriter
07:24:40   * software.amazon.ion.system.IonBinaryWriterBuilder
07:24:40   * software.amazon.ion.system.IonSystemBuilder
07:24:40   * software.amazon.ion.system.IonTextWriterBuilder
07:24:40   * software.amazon.ion.system.IonWriterBuilder
07:24:40 
07:24:40 > Task :qa:logging-config:jarHell
07:24:48 > Task :plugins:ingest-attachment:thirdPartyAudit
07:24:50 
07:24:50 > Task :plugins:discovery-azure-classic:thirdPartyAudit
07:24:50 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
07:24:51 Unnecessary exclusions, following classes are not missing:
07:24:51    * com.sun.xml.fastinfoset.stax.StAXDocumentParser
07:24:51   * javax.activation.FileTypeMap
07:24:51   * org.apache.log.Hierarchy
07:24:51   * org.apache.log.Logger
07:24:51   * org.eclipse.persistence.oxm.XMLField
07:24:51   * org.jvnet.fastinfoset.VocabularyApplicationData
07:24:51   * org.jvnet.staxex.Base64Data
07:24:51   * org.jvnet.staxex.XMLStreamReaderEx
07:24:51   * org.osgi.framework.BundleEvent
07:24:51 
07:24:51 > Task :plugins:discovery-azure-classic:thirdPartyAudit FAILED
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+EAR/24/console
https://scans.gradle.com/s/pea7qmxwfjvwm

**Comment by davidkyle** [comment]
And HDFS

```
20:55:48 > Task :plugins:discovery-azure-classic:thirdPartyAudit FAILED
20:55:48 Unnecessary exclusions, following classes are not missing:
20:55:48    * com.sun.xml.fastinfoset.stax.StAXDocumentParser
20:55:48   * com.sun.xml.fastinfoset.stax.StAXDocumentSerializer
20:55:48   * javax.servlet.ServletContextEvent
20:55:48   * javax.servlet.ServletContextListener
20:55:48   * org.apache.avalon.framework.logger.Logger
20:55:48   * org.apache.log.Hierarchy
20:55:48   * org.apache.log.Logger
20:55:48   * org.eclipse.persistence.descriptors.ClassDescriptor
20:55:48   * org.eclipse.persistence.internal.oxm.MappingNodeValue
20:55:48   * org.eclipse.persistence.internal.oxm.TreeObjectBuilder
20:55:48   * org.eclipse.persistence.internal.oxm.XPathFragment
20:55:48   * org.eclipse.persistence.internal.oxm.XPathNode
20:55:48   * org.eclipse.persistence.internal.queries.ContainerPolicy
20:55:48   * org.eclipse.persistence.jaxb.JAXBContext
20:55:48   * org.eclipse.persistence.jaxb.JAXBHelper
20:55:48   * org.eclipse.persistence.mappings.DatabaseMapping
20:55:48   * org.eclipse.persistence.mappings.converters.TypeConversionConverter
20:55:48   * org.eclipse.persistence.mappings.foundation.AbstractCompositeDirectCollectionMapping
20:55:48   * org.eclipse.persistence.oxm.XMLContext
20:55:48   * org.eclipse.persistence.oxm.XMLDescriptor
20:55:48   * org.eclipse.persistence.oxm.XMLField
20:55:48   * org.eclipse.persistence.oxm.mappings.XMLCompositeCollectionMapping
20:55:48   * org.eclipse.persistence.sessions.DatabaseSession
20:55:48   * org.jvnet.fastinfoset.VocabularyApplicationData
20:55:48   * org.jvnet.staxex.Base64Data
20:55:48   * org.jvnet.staxex.XMLStreamReaderEx
20:55:48   * org.jvnet.staxex.XMLStreamWriterEx
20:55:48   * org.osgi.framework.BundleEvent
20:55:48   * org.osgi.framework.SynchronousBundleListener
20:55:49 
20:55:49 > Task :plugins:discovery-gce:thirdPartyAudit
20:55:49 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
20:55:49 
20:55:49 > Task :modules:lang-painless:thirdPartyAudit
20:55:49 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
20:55:55 
20:55:55 > Task :plugins:repository-hdfs:thirdPartyAudit
20:55:55 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
20:55:55 
20:55:55 > Task :plugins:transport-nio:thirdPartyAudit
20:55:55 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
20:55:56 
20:55:56 > Task :plugins:repository-hdfs:thirdPartyAudit FAILED
20:55:56 Unnecessary exclusions, following classes have no violations:
20:55:56    * com.google.common.primitives.UnsignedBytes$LexicographicalComparatorHolder$UnsafeComparator
20:55:56   * com.google.common.primitives.UnsignedBytes$LexicographicalComparatorHolder$UnsafeComparator$1
20:55:56   * org.apache.hadoop.crypto.CryptoStreamUtils
20:55:56   * org.apache.hadoop.hdfs.shortcircuit.ShortCircuitShm
20:55:56   * org.apache.hadoop.hdfs.shortcircuit.ShortCircuitShm$Slot
20:55:56   * org.apache.hadoop.io.FastByteComparisons$LexicographicalComparerHolder$UnsafeComparer
20:55:56   * org.apache.hadoop.io.FastByteComparisons$LexicographicalComparerHolder$UnsafeComparer$1
20:55:56   * org.apache.hadoop.io.nativeio.NativeIO
20:55:56   * org.apache.hadoop.io.nativeio.NativeIO$POSIX
20:55:56   * org.apache.hadoop.security.SecurityUtil$QualifiedHostResolver
20:55:56   * org.apache.hadoop.util.SignalLogger$Handler
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+EAR/10/console

**Comment by original-brownbear** [comment]
@atorok this is all fixed by https://github.com/elastic/elasticsearch/pull/43956 right?

**Comment by atorok** [comment]
The EAR jobs are I think failing for  a different reason that has to do with those workers as it only happens there. Most likely an infrastructure issue.

**Comment by tvernum** [comment]
@atorok Is there are tracking issue for the worker problem? I can find one anywhere, and the builds are still failing.

**Comment by atorok** [comment]
I haven't created an infra issue yet,  I was hoping to be able to look at this sooner and provide more context on what can be wrong on the workers. I'll do that Today

**Comment by benwtrent** [comment]
Two more EAR build failures: 

https://scans.gradle.com/s/gwxwnjshijhf6/
https://scans.gradle.com/s/anofmmon6a7se/

Both were on Ubuntu 16.04.4 LTS, Linux 4.4.0-1061-aws

**Comment by benwtrent** [comment]
Another failure with similar cause as the original failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.3+multijob+third-party-tests-s3/17/console

```
Missing classes:
* com.amazonaws.services.kms.AWSKMS
* com.amazonaws.services.kms.AWSKMSClient
* com.amazonaws.services.kms.model.DecryptRequest
* com.amazonaws.services.kms.model.DecryptResult
* com.amazonaws.services.kms.model.EncryptRequest
* com.amazonaws.services.kms.model.EncryptResult
* com.amazonaws.services.kms.model.GenerateDataKeyRequest
* com.amazonaws.services.kms.model.GenerateDataKeyResult
```

running on Ubuntu 16.04.6 LTS, Linux 4.15.0-1036-gcp

**Comment by original-brownbear** [comment]
Ah damn, didn't backport this one to `7.3`. Will do shortly, reopening here until then.

**Comment by atorok** [comment]
The EAR build failures are due to elastic/infra#13000 ( OOM killer ) and #44269 should help with that.

**Comment by original-brownbear** [comment]
Closing here, this fix needed in S3 was already brought into `7.3` in https://github.com/elastic/elasticsearch/commit/8a731ddce1fbc2617fedb8242f36c5af904b77cc so no action left to take here imo.
