### ISSUE TITLE
es.http.cname_in_publish_address deprecation warning emitted even if not set

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#47436]
In #45616 we added a deprecation warning to encourage users to remove the `es.http.cname_in_publish_address` property that we added to support BWC across a 6.x/7.x upgrade. However this warning is emitted whenever `es.http.cname_in_publish_address` is true, which is the default, so it's emitted even if the property is unset.

Relates https://discuss.elastic.co/t/deprecation-warnings-since-the-upgrade-to-7-4-0/201917/3

**Comment by original-brownbear** [comment]
Fixed in #47451 and #47497

**Comment by baunz** [comment]
Hi! 

Is this really fixed? We just updated to 7.4.2 from 7.4.0 but still see multiple messages like this per second in our deprecation log even if we don't have this property set in our elasticsearch.yml

Greetings,
Johannes

**Comment by original-brownbear** [comment]
@baunz that property should be (if it's set) in your `jvm.options` not `elasticsearch.yml`. Could you double-check there please?

**Comment by jockjiang** [comment]
I have the same issue with 7.4.2, and I'm sure I don't set es.http.cname_in_publish_address property.

**Comment by original-brownbear** [comment]
@jockjiang could you check the [nodes stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-info.html) to check the actual JVM options used by your node(s)? If the system property is still in there, it's being picked up from somewhere in your system. It seems unlikely that this is still not fixed in `7.4.2` or that it's a system specific issue for you that isn't the result of the system property leaking in from somehwere.

**Comment by jockjiang** [comment]
@original-brownbear , I attached the result from the API. please review. I find "-Des.http.cname_in_publish_address=true"  in the JVM options.
[node_jvm.txt](https://github.com/elastic/elasticsearch/files/4535468/node_jvm.txt)

**Comment by original-brownbear** [comment]
@jockjiang yea so this really looks like you have the option set in your configs. Probably in the `jvm.options` in your `/etc/elasticsearch` folder. I'd look into there. If you're having trouble working out the issue from there, I'd suggest asking a question on our [discuss forums](https://discuss.elastic.co/) as why generally reserve Github for issue reporting and feature requests.
