### ISSUE TITLE
TokenAuthIntegTests testExpiredTokensDeletedAfterExpiration failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#56903]
**Build scan**:
https://gradle-enterprise.elastic.co/s/ashtsylpihoek

**Repro line**:
```
./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.testExpiredTokensDeletedAfterExpiration" \
  -Dtests.seed=46B9C42D9927439 \
  -Dtests.security.manager=true \
  -Dtests.locale=es \
  -Dtests.timezone=America/Lower_Princes \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

**Reproduces locally?**:
No

**Applicable branches**:
7.7

**Failure history**:
Rare, once in the last 30 days so I will not mute the test today

Possibly related to https://github.com/elastic/elasticsearch/issues/55816

**Failure excerpt**:
```
java.lang.AssertionError: 
Expected: <0>
     but: was <1>
	at __randomizedtesting.SeedInfo.seed([46B9C42D9927439:54A885BE2D43B28]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.testExpiredTokensDeletedAfterExpiration(TokenAuthIntegTests.java:226)
```

**Comment by dimitris-athanasiou** [comment]
Another failure:

Build scan: https://gradle-enterprise.elastic.co/s/3nxloq2igu22k

Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.9+multijob-unix-compatibility/os=debian-8&&immutable/30/console

**Comment by tvernum** [comment]
I've merged a change (#60496) which will improve this error message.

It's currently failing because a list of errors should be empty, but isn't.
But the code asserts on the `.size()` of the list, which leads to  `expected: <0> but: was <1>` messages.
It now asserts using `Matchers.empty()` which will include the value of the elements in the list (the unexpected errors) in the message.

**Comment by nik9000** [comment]
Another one! https://gradle-enterprise.elastic.co/s/zfxecuypvctq2

**Comment by tvernum** [comment]
The new assertion did the trick:
> Exception java.lang.AssertionError: 	
> Expected: an empty collection	
>     but: <[ElasticsearchException[Error invalidating refresh_token: ]; nested: DocumentMissingException[[_doc][token_OWGlJxnUGbJrMd8zNy2dQehL7tU0oQX6CCG1sZGaj08]: document missing];]>

**Comment by ywangd** [comment]
This `DocumentMissingException` failure is weird. I wonder whether it could also be caused by [dirty read](https://github.com/elastic/elasticsearch/issues/52400)?

**Comment by tvernum** [comment]
Yes, I'm pretty sure it is.
There's 2 problems

1. The token service doesn't deal with an already-invalidated document being deleted while we're attempting to invalidated it again
2. The test is susceptible to dirty reads.

I'm working on a fix to 1, and then I'll probably just put in an `assertBusy` to deal with the 2nd part since it's purely a test issue.

**Comment by nik9000** [comment]
Another one I think:
```
org.elasticsearch.xpack.security.authc.TokenAuthIntegTests > testExpiredTokensDeletedAfterExpiration FAILED
    java.lang.AssertionError: 
    Expected: an empty collection
         but: <[ElasticsearchException[Error invalidating refresh_token: ]; nested: DocumentMissingException[[_doc][token_3zAHHuUNXtsfC74xGfTOyHkPD4VebHI7TT9odnFQojw]: document missing];]>
        at __randomizedtesting.SeedInfo.seed([6796FD2557537C50:66B7E93C6C153341]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.security.authc.TokenAuthIntegTests.testExpiredTokensDeletedAfterExpiration(TokenAuthIntegTests.java:231)
:x-pack:test:smb-fixture:composeDown
:x-pack:qa:third-party:active-directory:check
```

https://gradle-enterprise.elastic.co/s/gwu2roq7rbheq/

**Comment by tvernum** [comment]
Well that's no good.  That should have been fixed by https://github.com/elastic/elasticsearch/pull/64682 

I guess it's back to analysis...

**Comment by ywangd** [comment]
Looking at #64682, it now seems to be obvious that the same issue can still happen. Because the document could be invalidated and deleted right after the `parseTokenAndRefreshStatus(..)` [call](https://github.com/elastic/elasticsearch/blob/7.x/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java#L663-L664) and subsequently runs into the same problem of missing document. Basically this is because status check and actual invalidation are not a single atomic operation.
