### ISSUE TITLE
Aggregating _ignored field values

### ISSUE THREAD

**Issue by aclowkey** [elastic/elasticsearch#59946]
When dealing with lots of data and lots of users, having the `ignore_malformed` option is great!
And using it in combination with _ignored field can give a lot of information about what is wrong with the data.

But unfortunately we can't aggregate on it, so it's hard to give an overview of which fields had issues in the last X hours.

I think it would be very useful to add .keyword for _ignored field, or make the _ignored field tokenised.

**Comment by jtibshirani** [comment]
We had an initial discussion and agreed that it seems useful to be able to aggregate over the `_ignored` field. We didn't reach a final conclusion but plan to continue the discussion. Other notes:
* We'd like to avoid adding another option to the mapping like `"doc_values": true`. However we weren't sure if it was worth the cost to always enable `doc_values`.
* One idea was to always enable `doc_values`, but stop adding the field as a stored field. The fetch phase would switch to retrieve `_ignored` from doc values.

**Comment by aclowkey** [comment]
Thanks for responding!

What's the cost difference for enabling doc_values?
I mean at scale there could be lots of _ignored fields, could the cost be
amplified hugely?

**Comment by davishmcclurg** [comment]
We recently started looking at using `ignore_malformed` in Enterprise Search. Being able to aggregate on the `_ignored` field would be super helpful for showing users what field types make sense for their data. Let me know if you're interested and I can explain a little bit more about our use case.

**Comment by jimczi** [comment]
We discussed internally and agreed to always enable doc_values, but stop adding the field as a stored field. The fetch phase would switch to retrieve _ignored from doc values as Julie proposed. @aclowkey would you still be interested to address this in your [PR](https://github.com/elastic/elasticsearch/pull/60103) ?

**Comment by aclowkey** [comment]
@jimczi I addressed it. I hope I didn't misunderstood you.
Please review

**Comment by javanna** [comment]
This came up again as we are using the `_ignored` field also for fields that have a script configured. In case the script fails, the document may still get indexed (with `on_script_error` set to `continue`) but the field name goes in the `_ignored` field. Yet another reason to enable doc_values for the `_ignored` field.

**Comment by nik9000** [comment]
>         "script" : { "source" : """emit(params['_fields']._ignored.value)""" }

I think
```
"""
for (def v : params['_fields']._ignored.values) {
  emit(v);
}
"""
```

We'd talked about a version of emit that took a list but never built it. It'd more complex than it sounds like.
