### ISSUE TITLE
Painless convenience functions for parsing URLs

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#60660]
Perhaps either whitelist [URL](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html) or wrapping that function.

Should be able to get scheme, host, port, path, fragment.

Meta: https://github.com/elastic/elasticsearch/issues/60659

**Comment by stu-elastic** [comment]
Looks like we can whitelist [java.net.URL](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html)

**Comment by interpreter95** [comment]
I'll whitelist [java.net.URL](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html) based on how the CIDR api was whitelisted in #71258

**Comment by GiBot2** [comment]
The issue originally said that allowing the URL class was a solution. There are commits here called "Whitelist URL class".
Does this mean that the issue is solved and can be closed, or is there something left to do? I would like to help if there is something left.

**Comment by interpreter95** [comment]
Hi @GiBot2 ,

This issue is not yet solved from what I know.

The "whitelist URL class" pull request that I created was meant to allow (or whitelist) the URL class in the Painless DSL language.

However, there was/is some problems with whitelisting the URL class (see #71709) and therefore the pull request was put on hold until we figure out how to solve the issue.

@stu-elastic did we figure out how we should proceed? Maybe it's better to wrap the URL class rather than whitelisting it?

**Comment by stu-elastic** [comment]
Hi @GiBot2 and @interpreter95 after some thoughts, we're going to handle this by exposing the existing [URI parts](https://www.elastic.co/guide/en/elasticsearch/reference/master/uri-parts-processor.html) processor in other contexts, see: https://github.com/elastic/elasticsearch/issues/74304.

Thank you for your PRs, both were headed in a good direction, but the reuse in #74304 is compelling.

**Comment by rjernst** [comment]
closing in favor of https://github.com/elastic/elasticsearch/issues/74304
