### ISSUE TITLE
A clean git checkout fails on integration tests in build-tools (master)

### ISSUE THREAD

**Issue by dweiss** [elastic/elasticsearch#63303]
A clean ES master checkout fails BWC integration tests. Here is the repro:
```
> git --version
git version 2.17.1
> uname -a
Linux -- 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> java -version
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
> git clone https://github.com/elastic/elasticsearch.git es
> cd es

> ./gradlew :build-tools:check

...
org.elasticsearch.gradle.internal.InternalBwcGitPluginFuncTest > current repository can be cloned FAILED
    org.gradle.testkit.runner.UnexpectedBuildFailure at InternalBwcGitPluginFuncTest.groovy:45
...
67 tests completed, 4 failed

> Task :build-tools:integTest FAILED
```

An example build scan is here:
https://scans.gradle.com/s/6smpe3tmmkeys

**Comment by dweiss** [comment]
The problem is somewhere in manual parsing of refs. I don't know the reason why it has to be custom code - this comment:

```
    public static GitInfo gitInfo(File rootDir) {
        try {
            /*
             * We want to avoid forking another process to run git rev-parse HEAD. Instead, we will read the refs manually. 
```

If you used a jgit dependency from within the build script (plugin) then it wouldn't have to be a forked process and jgit is fairly good at making sense of any git repository structure. Is this custom code really worth maintenance over a minor speed gain?

**Comment by cbuescher** [comment]
@dweiss sorry to hear you are having trouble.
I  just tried a clean checkout on 34aaa8d and that particular goal in `build-tools` was working.
My environment:
```
git version 2.24.3 (Apple Git-128)
openjdk version "14.0.1" 2020-04-14
```

I think @elastic/es-core-infra is best equiped to answer your question.

**Comment by droberts195** [comment]
Same thing is happening in CI on Windows every day - see https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/os=windows-2012-r2

I opened #63232 for this yesterday.

**Comment by dweiss** [comment]
I think this is git version specific, not operating system specific. I didn't look at ref parsing code deeply... why bother if you can use jgit for this - these folks have to provide support for various git flavors anyway.

**Comment by rjernst** [comment]
@mark-vieira Can you comment on not using jgit? I remember you moved us away from that for the performance gains, but it seems we either need that, or need better handling of the many ways git repositories can look?

**Comment by mark-vieira** [comment]
The reason for not using `jgit` was that it doesn't support worktrees.

**Comment by mark-vieira** [comment]
This seems to be specific to the git repo we are initializing for the purposes of our functional tests. This same logic works for the "outer" build so something different is going on in the test setup. @breskeby do you mind investigating this? We might have to add some additional logging to capture what's going on and why the `refs/` directory doesn't contain what we expect it to.

**Comment by dweiss** [comment]
bq. This seems to be specific to the git repo we are initializing for the purposes of our functional tests.

Precisely because the same code works at the top-level.

**Comment by breskeby** [comment]
I pushed a fix for #63232 which should also fix this issue here. @dweiss can you confirm this is fixed on the latest master?

**Comment by dweiss** [comment]
Still failing with the same error [ed4d1e3d3e45091]. Build scan:
https://gradle.com/s/drogbhf6kmcak

**Comment by dweiss** [comment]
But I think it fails for a different reason - the test fails with:
```
* What went wrong: |  
-- | --
  | Execution failed for task ':distribution:bwc:bugfix:buildBwcDarwinTar'. |  
  | > JAVA14_HOME required
```

I think it should complain about it at the master build level, not from within the test. I exported this env variable and then it passes.

**Comment by dweiss** [comment]
with JAVA14_HOME set:
https://gradle.com/s/ivggjxqkovgxg

**Comment by breskeby** [comment]
@dweiss that seems unrelated to this particular issue. I'm closing this ticket

**Comment by dweiss** [comment]
Maybe the cause is unrelated but the net effect for somebody who checks out elasticsearch and runs tests is the same... Running with JDK14 it will end with a cryptic test failure.

**Comment by breskeby** [comment]
sorry I misunderstood your message. yeah fixing this here makes sense

**Comment by dweiss** [comment]
I think so too.

**Comment by breskeby** [comment]
I changed the mocked git repo to build to rely on JDK12_HOME which is documented to be required by the elasticsearch build in our `contributing.md` file. Can you double check @dweiss

**Comment by dweiss** [comment]
Documented is one thing but could the build *fail* if you don't have any of the env. variables set? This is the key I think.

**Comment by dweiss** [comment]
I mean fail with a reasonable message like "JDK12_HOME is not set, see contributing.md"... :)

**Comment by breskeby** [comment]
I've created https://github.com/elastic/elasticsearch/issues/63480 as a follow up. I agree that ideally the build would fail as early as possible when certain prerequisites are not met. But For now I think we can close this issue as when you follow contributing.md in your es setup the build-tools should not fail anymore.

**Comment by dweiss** [comment]
Thanks Rene. I don't intend to be a pain but if it happened to me then it's likely to happen to more people... Better improve it once.

**Comment by dweiss** [comment]
Correct, works. Thanks!
