### ISSUE TITLE
Rescorer ignores track_score

### ISSUE THREAD

**Issue by afoucret** [elastic/elasticsearch#6788]
The track_scores param is ignored when combined with the rescore features.
This is not the behavior I expect with this feature.

Can you confirm this is a bug ?
If so can we excpect a bugfix ?

Thanks,

**Comment by Wedjaa** [comment]
Hi - any news on this feature? 
 Is there another way of using rescoring and sorting in the same query?

**Comment by clintongormley** [comment]
Hi @Wedjaa 

You may find the `terminate_after` parameter in http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html a useful alternative to rescoring.

**Comment by Wedjaa** [comment]
Hi @clintongormley,

looked into it, but I don't seem to be able to figure out how it substitutes rescoring. Am I missing something here?

The use case: search for some inexpensive query, rescore using expensive queries and then sort by relevance scoring and - for example - item name. I don't think is such an extreme case, considering that rescoring is targeted to exactly this use case - minus the sorting.

I'm at a loss on why the score is not added to the hits; especially considering that enabling "explain" the hits will contain the rescored value in the explanation; which means is somehow available when the hits are merged together to be given out as a response.

  cheers
  Fabio

**Comment by clintongormley** [comment]
@Wedjaa I don't know the details of why this change is complex - just taking it on trust.

Actually, ignore my comments about `terminate_after` - I realise that it doesn't fit here at all.

**Comment by tvarvadoukas** [comment]
Hey all! I would also agree that this is a very common usecase. It's a must-feature on our side as well. Are there any news on this?

**Comment by silashansen** [comment]
I've just done a simple test and it seems that this issue has been fixed and that sort is not disabling rescoring anymore.

First create some documents:
```
POST test/rescores
{
  "Title": "Document A"
}

POST test/rescores
{
  "Title": "Document B"
}
```

Query the index to see the what the response looks like without any sorting and rescoring:

```
GET test/rescores/_search
{
  "query": {
    "query_string": {
      "fields": ["Title"], 
      "query": "Document B"
    }
  }
}
```

Response:
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 0.78549397,
    "hits": [
      {
        "_index": "test",
        "_type": "rescores",
        "_id": "AV02FVaYJKvO25AaxC0D",
        "_score": 0.78549397,
        "_source": {
          "Title": "Document B"
        }
      },
      {
        "_index": "test",
        "_type": "rescores",
        "_id": "AV02FQv7JKvO25AaxC0C",
        "_score": 0.16358379,
        "_source": {
          "Title": "Document A"
        }
      }
    ]
  }
}
```

Now issue a request that includes both rescoring and sorting.

```
GET test/rescores/_search
{
  "query": {
    "query_string": {
      "fields": ["Title"], 
      "query": "Document B"
    }
  },
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    }
  ],
    "rescore": {
    "window_size": 100,
    "query": {
      "rescore_query": {
        "function_score": {
          "script_score": {
            "script": {
              "inline": "return 10"
            }
          },
          "boost_mode": "multiply"
        }
      },
      "query_weight": 1,
      "rescore_query_weight": 1
    }
  }
}
```

Response:

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 10.785494,
    "hits": [
      {
        "_index": "test",
        "_type": "rescores",
        "_id": "AV02FVaYJKvO25AaxC0D",
        "_score": 10.785494,
        "_source": {
          "Title": "Document B"
        }
      },
      {
        "_index": "test",
        "_type": "rescores",
        "_id": "AV02FQv7JKvO25AaxC0C",
        "_score": 10.163584,
        "_source": {
          "Title": "Document A"
        }
      }
    ]
  }
}

```

Now, it's obvious that the rescoring is in fact active, as the scores are clearly factored by the boost in the rescore query.

So, what is the status from Elastic on this? Should the docs be updated or am I misunderstanding something?

**Comment by javanna** [comment]
hi @silashansen unfortunately this issue wasn't solved. I can still reproduce the initial recreation above. I suspect everything works in your case because your sort clause is the default one, as you are sorting by score descending which is the same as leaving the sort clause out of the request.

**Comment by silashansen** [comment]
You are absolutely right - what a shame!
Is it anywhere on the roadmap to get this fixed?

**Comment by jimczi** [comment]
The issue reported here is not a bug and cannot be "fixed". The rescorer by design should always rescore top hits sorted by `_score`. It's the only way to have the correct behavior because rescoring is done at the shard level. In the recreation of this issue the rescorer is used on a result sorted by something else than `_score`, a field named `position`. To get the N best documents sorted by `position` we need to fetch the N best results for all shards. 
Though the rescoring reorders the top N+M with a function score at the shard level and returns a new top N. So it's not returning the best N documents per shard sorted by position but the best N documents sorted by the function score among the N+M best documents sorted by position. 
To be accurate the rescoring should be applied to the N best documents  globally, not per shard, otherwise the returned documents may not represent the first sort.

I am closing this issue because this is a known limitation. Rescoring works only when _score is the first sort criteria.
