### ISSUE TITLE
Unable to index large geo_shape

### ISSUE THREAD

**Issue by nreese** [elastic/elasticsearch#69890]
While working on geojson upload within Kibana, we ran across a monster feature that is over 2MB that appears to break indexing in elasticsearch. The indexing request just times out.

I do not expect elasticsearch to handle such a large feature but would be wondering if its possible to have some kind of circuit breaker where the feature could fail indexing in a timely manor. Or, is there a well known limit to the size of features that can be indexed so we can avoid passing these features to Elasticsearch in the first place?

You can view the behavior by running the following commands in dev tools. But first, set kibana.yml `server.maxPayloadBytes: 5048576` so the command can run

```
PUT test
{}

PUT test/_mapping
{
  "properties": {
    "coordinates": {
      "type": "geo_shape"
    }
  }
}
```

Working feature to test index setup
```
PUT test/_doc/1
{"coordinates":{"type":"polygon","coordinates":[[[50.258333,30.575],[50.266667,30.575],[50.266667,30.583333],[50.275,30.583333],[50.283333,30.583333],[50.283333,30.591667],[50.275,30.591667],[50.266667,30.591667],[50.266667,30.6],[50.266667,30.608333],[50.275,30.608333],[50.275,30.616667],[50.266667,30.616667],[50.266667,30.625],[50.258333,30.625],[50.258333,30.616667],[50.25,30.616667],[50.241667,30.616667],[50.233333,30.616667],[50.225,30.616667],[50.216667,30.616667],[50.216667,30.608333],[50.216667,30.6],[50.216667,30.591667],[50.216667,30.583333],[50.225,30.583333],[50.225,30.575],[50.233333,30.575],[50.233333,30.566667],[50.241667,30.566667],[50.25,30.566667],[50.258333,30.566667],[50.258333,30.575]],[[50.258333,30.575],[50.25,30.575],[50.25,30.583333],[50.258333,30.583333],[50.258333,30.575]]]},"name_conve":"Behbehan","max_pop_al":85707,"max_pop_20":85707,"max_pop_50":0,"max_pop_30":0,"max_pop_31":0,"max_natsca":20,"min_areakm":26,"max_areakm":26,"min_areami":10,"max_areami":10,"min_perkm":31,"max_perkm":31,"min_permi":19,"max_permi":19,"min_bb_xmi":50.21666667,"max_bb_xmi":50.21666667,"min_bb_xma":50.28333333,"max_bb_xma":50.28333333,"min_bb_ymi":30.56666667,"max_bb_ymi":30.56666667,"min_bb_yma":30.625,"max_bb_yma":30.625,"mean_bb_xc":50.24559524,"mean_bb_yc":30.59535714}
```

Monster feature that causes timeouts. Down load https://github.com/nreese/notes/blob/master/index_large_feature_cmd.txt and run in Kibana console.

**Comment by imotov** [comment]
This shape doesn't break indexing in elasticsearch, it just 1) takes a long time to index (46s on my machine) and 2) it cannot be indexed because it is malformed and cannot be tessellated by elasticsearch. As a result it causes kibana to timeout. If you set `elasticsearch.requestTimeout` to something large, you eventually get the following error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [coordinates] of type [geo_shape]"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [coordinates] of type [geo_shape]",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Unable to Tessellate shape [.... A LOT OF COORDINATES HERE ....]. Possible malformed shape detected."
    }
  },
  "status" : 400
}
```

If I understood you correctly, the desire is to setup a some sort of a circuit breaker that would prevent a very large shapes from being indexed. I am going to rename the issue accordingly.

**Comment by iverase** [comment]
The shape is actually ok. It is a bug in Lucene's Tessellator the reason why the polygon failing. I will fill an issue shortly.

**Comment by iverase** [comment]
This should have been fixed in here:  https://issues.apache.org/jira/browse/LUCENE-9580

**Comment by iverase** [comment]
Hi @nreese,

We discussed this issue and the first thing is that in our point of view, we expect Elasticsearch to be able to handle large features. There was a bug in Lucene which is now fixed, so this feature should be handle properly in future versions.

Still, it will take a fair amount of time to process this single shape. This is due not only because the geometry has lots of vertices but because it has lots of holes which makes the processing slower. The issue here is that we are not sure how we can measure the complexity of a geometry as there is no a single metric for that.

Can you explain a bit deeper what are your expectations regarding `complex shapes`? e.g what should be consider complex, and be rejected by the new circuit breaker.

**Comment by wchaparro** [comment]
Hey @nreese is this still a need for the Kibana team?

**Comment by nreese** [comment]
> Can you explain a bit deeper what are your expectations regarding complex shapes

I would define complex shapes as one with lots of holes.

> Hey @nreese is this still a need for the Kibana team?

Yes, it would be great if there could be some kind of circuit breaker for indexing complex shapes. It's still a problem but I am unsure how many users are effected since most used cases seem to be simpler shapes

**Comment by wchaparro** [comment]
related to https://github.com/elastic/elasticsearch/issues/44747
