### ISSUE TITLE
[CI] SSLDriverTests testHandshakeFailureBecauseProtocolMismatch failing

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#72122]
Only reproduces on Zulu jvms. Reproduced for me locally with Zulu 11.0.11.

**Build scan:**
https://gradle-enterprise.elastic.co/s/ctngyizquooci/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.security.transport.nio.SSLDriverTests/testHandshakeFailureBecauseProtocolMismatch

**Reproduction line:**
`./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch" -Dtests.seed=98E8EE60436E9816 -Dtests.locale=mt-MT -Dtests.timezone=Australia/Lindeman -Druntime.java=11`

**Applicable branches:**
master, 7.x, 7.13

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.transport.nio.SSLDriverTests&tests.test=testHandshakeFailureBecauseProtocolMismatch

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: (is "The client supported protocol versions [TLSv1.1] are not accepted by server preferences [TLS12]" or is "Client requested protocol TLSv1.1 not enabled or not supported")
     but: was "No appropriate protocol (protocol is disabled or cipher suites are inappropriate)"

  at __randomizedtesting.SeedInfo.seed([98E8EE60436E9816:47DBCF1979E59BE]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch(SSLDriverTests.java:195)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:829)

```

**Comment by davidkyle** [comment]
Many failures all on Zulu, here's a selection

https://gradle-enterprise.elastic.co/s/vw4uyegzi3qno    - Zulu 8
https://gradle-enterprise.elastic.co/s/yv5wgreewhr7e  - Zulu 11
https://gradle-enterprise.elastic.co/s/bosjbotdvmfey
https://gradle-enterprise.elastic.co/s/odpbywq7u5chm

**Comment by mayya-sharipova** [comment]
Another failure today at 7.x: https://gradle-enterprise.elastic.co/s/ytoenq6hqhzeu

I guess with a backport to 7.x, the issue will be resolved

**Comment by mayya-sharipova** [comment]
Another failure on 7.12 branch: https://gradle-enterprise.elastic.co/s/6wtj6fltw5a3s

Needs backport to 7.12 as well.

**Comment by ywangd** [comment]
Thanks @mayya-sharipova This should now be fixed with #72348

**Comment by cbuescher** [comment]
I'm still seeing test failures related to these error messages today despite PR that has been merged above. Maybe a new problem? Here are some failures from the last 8 hours:
7.13


7.12: 
https://gradle-enterprise.elastic.co/s/ieac2filczczg
https://gradle-enterprise.elastic.co/s/vd2blhoykfclo

**Comment by cbuescher** [comment]
I muted SSLDriverTests#testHandshakeFailureBecauseProtocolMismatch on master, 7.x, 7.13 and 7.12

**Comment by ywangd** [comment]
Err this is what Tim had [suggested](https://github.com/elastic/elasticsearch/pull/72223#discussion_r620750410). The error message should not be tied to a specific JVM vendor. Zulu is normally the first one to backport and often times other vendors follow suit. I'll amend the fix to be more general. Thanks for re-openning it.
