### ISSUE TITLE
Execution failed for task ':qa:rolling-upgrade:v8.8.0#oneThirdUpgradedTest'.

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#96574]
### CI Link

https://gradle-enterprise.elastic.co/s/auzc7rymva2g4

### Repro line

./gradlew :qa:rolling-upgrade:v8.8.0#oneThirdUpgradedTest

### Does it reproduce?

Yes

### Applicable branches

8.8

### Failure excerpt
```
 [2023-06-05T13:17:33,878][WARN ][o.e.c.c.JoinHelper       ] [v8.8.0-0] last failed join attempt was 967ms ago, failed to join {v8.8.0-1}{Q30XLr6JTA6Z0OuQdZYSNA}{NFdzm0nsSAybBAkCCAsdJg}{v8.8.0-1}{127.0.0.1}{127.0.0.1:35155}{cdfhilmrstw}{8.8.0}{ml.allocated_processors=32, testattr=test, ml.allocated_processors_double=32.0, ml.machine_memory=101200584704, xpack.installed=true, ml.max_jvm_size=536870912} with JoinRequest{sourceNode={v8.8.0-0}{uUkkMrdaS2aNpQ2LnS8E9g}{xvFDghtqTUi4kaJWTFCBoA}{v8.8.0-0}{127.0.0.1}{127.0.0.1:41814}{cdfhilmrstw}{8.9.0}{upgraded=true, ml.allocated_processors=32, ml.allocated_processors_double=32.0, ml.max_jvm_size=536870912, xpack.installed=true, testattr=test, ml.machine_memory=101200584704}, transportVersion=8500007, minimumTerm=1, optionalJoin=Optional.empty} org.elasticsearch.transport.RemoteTransportException: [v8.8.0-1][127.0.0.1:35155][internal:cluster/coordination/join]	
»  Caused by: java.lang.IllegalStateException: failure when sending a join validation request from [{v8.8.0-1}{Q30XLr6JTA6Z0OuQdZYSNA}{NFdzm0nsSAybBAkCCAsdJg}{v8.8.0-1}{127.0.0.1}{127.0.0.1:35155}{cdfhilmrstw}{8.8.0}] to [{v8.8.0-0}{uUkkMrdaS2aNpQ2LnS8E9g}{xvFDghtqTUi4kaJWTFCBoA}{v8.8.0-0}{127.0.0.1}{127.0.0.1:41814}{cdfhilmrstw}{8.9.0}]	
»  	at org.elasticsearch.cluster.coordination.Coordinator.lambda$sendJoinValidate$13(Coordinator.java:730)	
»  	at org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:126)	
»  	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:59)	
»  	at org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:131)	
»  	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:59)	
»  	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:71)	
»  	at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27)	
»  	at org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:181)	
»  	at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:59)	
»  	at org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:71)	
»  	at org.elasticsearch.action.ActionListener$5.onFailure(ActionListener.java:339)	
»  	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:48)	
»  	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1405)	
»  	at org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:461)	
»  	at org.elasticsearch.transport.InboundHandler$3.doRun(InboundHandler.java:453)	
»  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)	
»  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)	
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)	
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)	
»  	at java.lang.Thread.run(Thread.java:1623)	
»  Caused by: org.elasticsearch.transport.RemoteTransportException: [v8.8.0-0][127.0.0.1:41814][internal:cluster/coordination/join/validate]	
»  Caused by: java.lang.IllegalStateException: unexpected byte [0x02]	
»  	at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:564)	
»  	at org.elasticsearch.common.io.stream.StreamInput.readBoolean(StreamInput.java:554)	
»  	at org.elasticsearch.common.io.stream.StreamInput.readOptionalTimeValue(StreamInput.java:1306)	
»  	at org.elasticsearch.cluster.metadata.DataLifecycle.<init>(DataLifecycle.java:143)	
»  	at org.elasticsearch.common.io.stream.StreamInput.readOptionalWriteable(StreamInput.java:1006)	
»  	at org.elasticsearch.cluster.metadata.Template.<init>(Template.java:161)	
»  	at org.elasticsearch.cluster.metadata.ComponentTemplate.<init>(ComponentTemplate.java:73)	
»  	at org.elasticsearch.common.io.stream.StreamInput.readMap(StreamInput.java:641)	
»  	at org.elasticsearch.common.io.stream.StreamInput.readMap(StreamInput.java:625)	
»  	at org.elasticsearch.cluster.metadata.ComponentTemplateMetadata.<init>(ComponentTemplateMetadata.java:62)	
»  	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:56)	
»  	at org.elasticsearch.common.io.stream.NamedWriteableAwareStreamInput.readNamedWriteable(NamedWriteableAwareStreamInput.java:32)	
»  	at org.elasticsearch.cluster.metadata.Metadata.readFrom(Metadata.java:1653)	
»  	at org.elasticsearch.cluster.ClusterState.readFrom(ClusterState.java:907)	
»  	at org.elasticsearch.cluster.coordination.ValidateJoinRequest.readCompressed(ValidateJoinRequest.java:59)	
»  	at org.elasticsearch.cluster.coordination.ValidateJoinRequest.lambda$new$0(ValidateJoinRequest.java:36)	
»  	at org.elasticsearch.cluster.coordination.ValidateJoinRequest.getOrReadState(ValidateJoinRequest.java:76)	
»  	at org.elasticsearch.cluster.coordination.JoinValidationService.lambda$new$2(JoinValidationService.java:121)	
»  	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:74)	
»  	at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:315)	
»  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)	
»  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)	
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)	
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)	
»  	at java.lang.Thread.run(Thread.java:1623)	
»  
```

**Comment by pxsalehi** [comment]
I think this is the same issue as in https://github.com/elastic/elasticsearch/issues/96382

**Comment by pxsalehi** [comment]
And I think it was fixed. But I let someone from the DM team to verify and close this if necessary.

**Comment by ywangd** [comment]
Still happening https://gradle-enterprise.elastic.co/s/b4wdlmpjrquic

Though the error message is a bit different in the above build scan
```
»  Caused by: org.elasticsearch.transport.RemoteTransportException: [v8.8.0-0][127.0.0.1:45429][internal:cluster/coordination/join/validate]
»  Caused by: java.lang.IllegalStateException: array length must be <= to 2147483631 but was: 2147483647
```

But when I run locally, it failed with the same "unexpected byte" error.

**Comment by HiDAl** [comment]
It hasn't happened in the last weeks and it seems to be related to this #96518. Closing the ticket
